### ISSUE TITLE
Allow the countries to accept a list.

### ISSUE THREAD

**Issue by skorokithakis** [jamiees2/dnsproxy#13]
I have a somewhat complicated use case that calls for accepting multiple countries' configs in the command line, so I can basically generate a haproxy config with all the settings. Would it be possible to allow the command to accept a comma-separated list of countries and load all the services?

I can work on this, if necessary, and submit a PR.

**Comment by jamiees2** [comment]
Sure, that seems like a very cool addition! I'm going away for a week, so I won't be able to work on it, but if you want to send a PR, go for it. I imagine it would just require concatenating the json data before processing.

**Comment by skorokithakis** [comment]
Yep, exactly. I'll work on it tomorrow, thank you!

**Comment by skorokithakis** [comment]
Sent the PR! It's pretty simple, it would be great if you could review and merge it soon, as I have code pointing to your repo. Thanks!
