### ISSUE TITLE
US proxy list seems to be broken

### ISSUE THREAD

**Issue by wangcho2k** [jamiees2/dnsproxy#28]
After the #27, the file `proxies-us.json` seems to be broken. When I invoked `python dnsproxy.py -o haproxy` to generate HAProxy configurations, I got an error :

<pre>Traceback (most recent call last):
  File "dnsproxy.py", line 239, in <module>
    main(args)
  File "dnsproxy.py", line 118, in main
    config = read_config(args)
  File "dnsproxy.py", line 97, in read_config
    groups.update(util.json_decode(util.get_contents("proxies/proxies-%s.json" % country)))
  File "/home/ykstyle/working/dnsproxy/util.py", line 20, in json_decode
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 863 column 1 - line 886 column 1 (char 19484 - 19936)</pre>

I found that lines from 863 to 885 are duplicated and broken pieces of existing lists so should be removed. After I removed them, the code worked fine.

**Comment by jamiees2** [comment]
Oh wow, I didn't notice that, I'm sorry :( 

It's been fixed in the latest commit on master :) 

Thanks for the catch!

**Comment by wangcho2k** [comment]
Thanks a lot for an immediate response 👍
